config/routes.rb
RailsWithCi::Application.routes.draw do
  resources :students

  root :to => "students#index"

end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :name, :address
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(params[:student])
    if @student.save
      redirect_to @student, :notice => "Successfully created student."
    else
      render :action => 'new'
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update_attributes(params[:student])
      redirect_to @student, :notice  => "Successfully updated student."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_url, :notice => "Successfully destroyed student."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
		def full_title(page_title)
		base_title = "SmartCoach"
		@page_title = page_title
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
		end

		def check_null(str)
			if str.empty?
				true
			else
				false
			end
		end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/students/edit.html.erb
<% provide(:title, 'Students') %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @student %> |
  <%= link_to "View All", students_path %>
</p>

app/views/students/index.html.erb
<% provide(:title, 'Students') %>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
  </tr>
  <% for student in @students %>
    <tr>
      <td><%= student.name %></td>
      <td><%= student.address %></td>
      <td><%= link_to "Show", student %></td>
      <td><%= link_to "Edit", edit_student_path(student) %></td>
      <td><%= link_to "Destroy", student, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Student", new_student_path %></p>

app/views/students/new.html.erb
<% provide(:title, 'Students') %>

<%= render 'form' %>

<p><%= link_to "Back to List", students_path %></p>

app/views/students/show.html.erb
<% provide(:title, 'Students') %>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>
<p>
  <strong>Address:</strong>
  <%= @student.address %>
</p>

<p>
  <%= link_to "Edit", edit_student_path(@student) %> |
  <%= link_to "Destroy", @student, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", students_path %>
</p>